# runs-on -> ubuntu-latest macos-latest windows-latest
name: GitHub Actions Demo
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: build and run tests
        run: make runbin
  other-stuff:
    runs-on: macos-latest
    steps:
      - run: uname -a
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: build and run tests
        run: make runbin
      
