# runs-on -> ubuntu-latest macos-latest windows-latest
name: GitHub Actions Demo
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: build and run tests
        run: make runbin
  other-stuff:
    runs-on: macos-latest
    steps:
      - run: uname -a
      - run: id
      - run: hostname
      - run: pwd
      - run: ifconfig
      
