# runs-on -> ubuntu-latest macos-latest windows-latest
name: GitHub Actions Demo
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: build and run tests
        run: make runbin
  mac:
    runs-on: macos-latest
    steps:
      - run: uname -a
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: build and run tests
        run: make runbin
  windows:
      runs-on: windows-latest
      steps:
        - run: uname -a
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: build and run tests
          run: make runbin
  
      
